Public Interface IJobParams
	'Used for job closeout
	Enum CloseOutType
		CLOSEOUT_SUCCESS = 0
		CLOSEOUT_FAILED = 1
		CLOSEOUT_NO_DTA_FILES = 2
		CLOSEOUT_NO_OUT_FILES = 3
		'		CLOSEOUT_NO_HTML_FILES = 4
		CLOSEOUT_NO_ANN_FILES = 5
		CLOSEOUT_NO_FAS_FILES = 6
	End Enum

	'******************************************************************
	'
	'	Parameters defined in this class:
	'		"jobNum"	--	Job number
	'		"datasetNum"	--	Dataset number
	'		"datasetFolderName"	--	Name of dataset folder (normally same as dataset number)
	'		"datasetFolderStoragePath"	--	Path to dataset folder in archive via Samba (ie, \\n2.emsl.pnl.gov\dmsarch\LCQ_1\LCQ_C2)
	'		"transferFolderPath"	--	Results transfer folder on storage server (ie, DMS3_Xfer\)
	'		"parmFileName"	-- Parameter file name
	'		"parmFileStoragePath"	--	Location where param file storage is located (not used for Sequest)
	'		"settingsFileName"	--	Name of settings file
	'		"settingsFileStoragePath"	--	Settings file storage location
	'		"instClass"	-- Instrument class for instrument that dataset was created on
	'		"comment"	--	Misc comments
	'		"tool"	-- Analysis tool for this job
	'		"priority"	-- Job priority
	'		"legacyFastaFileName  -- Fasta file name for legacy jobs (replaced organismDBName)
	'		"RawDataType"  -- Describes format of raw data (.wiff, .raw, folder, etc)
	'		"SearchEngineInputFileFormats"  --  Future use?
	'		"OrganismName"  -- Organism name
	'		"OrgDbReqd"  -- Flag to determine if an org db/protein collection is required for this analysis tool
	'		"ProteinCollectionList"  -- List of protein collections for this analysis job
	'		"ProteinOptionsList"  -- List of protein collection options for this analysis job
	'
	'	The following parameter(s) are generated during the analysis job performance
	'		"generatedFastaName"  -- Name of the fasta file generated by Ken's OTF fasta generation dll
	'
	'******************************************************************

	Function GetParam(ByVal Name As String) As String

	Function AddAdditionalParameter(ByVal ParamName As String, ByVal ParamValue As String) As Boolean

End Interface
