// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Leave for reference", Scope = "member", Target = "~M:AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter.CreateMSGFReportFile(System.Int32,System.String,AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter.FilterThresholds,System.String@)~System.Boolean")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Leave for reference", Scope = "member", Target = "~M:AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter.CreateMSGFReportXMLFile(System.String,AnalysisManagerBase.JobConfig.DataPackageJobInfo,System.String,System.Collections.Generic.IReadOnlyDictionary{System.String,System.Collections.Generic.List{AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter.PseudoMSGFData}},System.String,System.String,AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter.FilterThresholds)~System.String")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Leave for reference", Scope = "member", Target = "~M:AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter.CreateMzXMLFileIfMissing(System.String,AnalysisManagerBase.AnalysisTool.AnalysisResults,System.Collections.Generic.IReadOnlyDictionary{System.String,System.String})~System.Boolean")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Leave for reference", Scope = "member", Target = "~M:AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter.CreatePrideXMLFile(System.Int32,System.String,System.String,System.String@)~System.Boolean")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "Leave for reference", Scope = "member", Target = "~M:AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter.GetPrideConverterVersion(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Acceptable design pattern", Scope = "module")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses not needed", Scope = "member", Target = "~M:AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter.ComputeApproximateEValue(System.Double)~System.Double")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "Uses the preferred syntax", Scope = "member", Target = "~M:AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter.ReadTemplatePXSubmissionFile~System.Collections.Generic.Dictionary{System.String,System.String}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Acceptable legacy name", Scope = "type", Target = "~T:AnalysisManagerPRIDEConverterPlugIn.AnalysisResourcesPRIDEConverter")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Acceptable legacy name", Scope = "type", Target = "~T:AnalysisManagerPRIDEConverterPlugIn.AnalysisToolRunnerPRIDEConverter")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Acceptable legacy name", Scope = "type", Target = "~T:AnalysisManagerPRIDEConverterPlugIn.SampleMetadata")]
